apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: y5u27sgvi-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:309b25868be3ca592a133299ed3274f49b0fbffe@sha256:8d6e1d36cc2ccbb29ef164bf79a67a886a004e202933c200bac5cecf871f76a3
          name: container-image
