apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: y5u27sgvi-python 
  janus-idp.io/tekton: y5u27sgvi-python
  backstage.io/kubernetes-id: y5u27sgvi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: y5u27sgvi-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml